runtime: go
api_version: skinsavvy0.1
env: standard
env_variables:
  DATABASE_URL=${DATABASE_URL}
  GEMINI_API_KEY=${GEMINI_API_KEY}
  HOST=${HOST}
  PORT=${PORT}
  GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
  GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
  GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
handler:
- url: /.*